"""initial schema

Revision ID: 6a32c9c642ad
Revises: 
Create Date: 2026-07-31 06:36:47.189982

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a32c9c642ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_url', sa.String(length=1024), nullable=True),
    sa.Column('download_source_url', sa.String(length=1024), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('download_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.String(length=64), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_avatars',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'avatar_id')
    )
    op.create_table('item_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_item_id', sa.Integer(), nullable=True),
    sa.Column('free_text_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_role', sa.Enum('PRIMARY', 'THUMBNAIL', 'ATTACHMENT', name='filerole', native_enum=False, length=32), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('licenses',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('commercial_use', sa.Enum('YES', 'NO', 'UNKNOWN', name='tristate', native_enum=False, length=16), nullable=False),
    sa.Column('modification_allowed', sa.Enum('YES', 'NO', 'UNKNOWN', name='tristate', native_enum=False, length=16), nullable=False),
    sa.Column('redistribution_allowed', sa.Enum('YES', 'NO', 'UNKNOWN', name='tristate', native_enum=False, length=16), nullable=False),
    sa.Column('credit_required', sa.Enum('YES', 'NO', 'UNKNOWN', name='tristate', native_enum=False, length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Hand-added: search/filter query indexes (see item_service.search_items)
    op.create_index('ix_items_status_id', 'items', ['status_id'])
    op.create_index('ix_items_shop_id', 'items', ['shop_id'])
    op.create_index('ix_item_tags_tag_id', 'item_tags', ['tag_id'])
    op.create_index('ix_item_avatars_avatar_id', 'item_avatars', ['avatar_id'])


def downgrade() -> None:
    op.drop_index('ix_item_avatars_avatar_id', table_name='item_avatars')
    op.drop_index('ix_item_tags_tag_id', table_name='item_tags')
    op.drop_index('ix_items_shop_id', table_name='items')
    op.drop_index('ix_items_status_id', table_name='items')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_history')
    op.drop_table('licenses')
    op.drop_table('item_tags')
    op.drop_table('item_files')
    op.drop_table('item_dependencies')
    op.drop_table('item_avatars')
    op.drop_table('items')
    op.drop_table('tags')
    op.drop_table('statuses')
    op.drop_table('shops')
    op.drop_table('oauth_credentials')
    op.drop_table('avatars')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
